import { useGetReports, useGenerateReport } from "@workspace/api-client-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { FileText, Download, Clock, Plus, Filter } from "lucide-react";
import { format } from "date-fns";

export default function Reports() {
  const { data: reports, isLoading } = useGetReports();
  const generateMutation = useGenerateReport();

  const handleGenerate = () => {
    generateMutation.mutate({ data: { type: "weekly" } });
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Growth Reports</h1>
          <p className="text-muted-foreground">Executive summaries and deep-dives generated by AI.</p>
        </div>
        <Button onClick={handleGenerate} disabled={generateMutation.isPending} className="gap-2 bg-primary hover:bg-primary/90 text-primary-foreground">
          {generateMutation.isPending ? <Clock size={16} className="animate-spin" /> : <Plus size={16} />}
          Generate New Report
        </Button>
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between pb-2 border-b border-border/50">
          <div>
            <CardTitle>Report Archive</CardTitle>
            <CardDescription>All your historical generated reports</CardDescription>
          </div>
          <Button variant="outline" size="icon" className="h-8 w-8">
            <Filter size={14} />
          </Button>
        </CardHeader>
        <div className="p-0">
          {isLoading ? (
            <div className="p-6 space-y-4">
              {Array(4).fill(0).map((_, i) => <Skeleton key={i} className="h-16 w-full rounded-lg" />)}
            </div>
          ) : (
            <div className="divide-y divide-border/50">
              {reports?.map((report) => (
                <div key={report.id} className="flex items-center justify-between p-4 sm:p-6 hover:bg-secondary/20 transition-colors">
                  <div className="flex items-center gap-4">
                    <div className={`w-10 h-10 rounded-lg flex items-center justify-center border shrink-0 ${report.type === 'weekly' ? 'bg-primary/10 text-primary border-primary/20' : 'bg-accent/10 text-accent border-accent/20'}`}>
                      <FileText size={20} />
                    </div>
                    <div>
                      <h4 className="font-bold text-base mb-1 flex items-center gap-2">
                        {report.type === 'weekly' ? 'Weekly' : 'Monthly'} Growth Summary
                        {report.status === 'generating' && (
                          <span className="px-2 py-0.5 text-[10px] uppercase tracking-wider font-bold bg-secondary text-muted-foreground rounded-full flex items-center gap-1">
                            <Clock size={10} className="animate-spin" /> Generating
                          </span>
                        )}
                      </h4>
                      <p className="text-sm text-muted-foreground font-mono">
                        Period: {report.period} • Generated {format(new Date(report.createdAt), 'MMM dd, yyyy')}
                      </p>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    <Button variant="outline" size="sm" disabled={report.status !== 'ready'} className="hidden sm:flex gap-2">
                      <EyeIcon size={14} /> View
                    </Button>
                    <Button variant="secondary" size="icon" disabled={report.status !== 'ready'} title="Download PDF">
                      <Download size={16} />
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}

// Quick inline icon component to avoid an extra import line above
function EyeIcon(props: any) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={props.size || 24} height={props.size || 24} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}