/**
 * OAuthService
 * Orchestrates OAuth provider operations using the factory pattern.
 * Business logic that applies across all providers lives here.
 * Provider-specific logic lives in individual BaseOAuthProvider subclasses.
 */

import OAuthProviderFactory from './oauth/OAuthProviderFactory.js';
import ConnectedAccountRepository from '../repositories/ConnectedAccountRepository.js';
import { NotFoundError } from '../utils/errors.js';
import logger from '../utils/logger.js';

const OAuthService = {
  /**
   * Get all supported OAuth platforms and their implementation status.
   * Used to inform the frontend which providers are available.
   */
  getSupportedPlatforms() {
    return OAuthProviderFactory.getSupportedPlatforms().map((platform) => ({
      platform,
      implemented: OAuthProviderFactory.isImplemented(platform),
    }));
  },

  /**
   * Initiate an OAuth connection flow for a platform.
   * Returns the authorization URL to redirect the user to.
   *
   * @param {string} platform
   * @param {string} state     CSRF state token (generated by controller)
   * @returns {string}         Authorization URL
   */
  getAuthorizationUrl(platform, state) {
    const provider = OAuthProviderFactory.getProvider(platform);
    return provider.getAuthorizationUrl(state);
  },

  /**
   * Complete an OAuth connection after the provider redirects back.
   * Exchanges the code for tokens, fetches the profile, saves the account.
   *
   * @param {string} userId
   * @param {string} platform
   * @param {string} code
   * @returns {Promise<object>}  Public view of the saved ConnectedAccount
   */
  async connect(userId, platform, code) {
    const provider = OAuthProviderFactory.getProvider(platform);
    const result = await provider.connect(userId, code);
    logger.info('Platform connected via OAuth', { userId, platform });
    return result;
  },

  /**
   * Disconnect a user from a platform.
   * Revokes tokens at the provider level if supported, then soft-deletes the account.
   *
   * @param {string} userId
   * @param {string} platform
   */
  async disconnect(userId, platform) {
    const existing = await ConnectedAccountRepository.findByUserAndPlatform(userId, platform);
    if (!existing) throw new NotFoundError(`${platform} account`);

    try {
      const provider = OAuthProviderFactory.getProvider(platform);
      await provider.disconnect(userId);
    } catch (err) {
      // Provider may not be implemented yet — fall through to soft-delete
      logger.warn('Provider disconnect failed (may not be implemented)', {
        userId,
        platform,
        error: err.message,
      });
    }

    await ConnectedAccountRepository.softDeleteByUserAndPlatform(userId, platform);
    logger.info('Platform disconnected', { userId, platform });
  },

  /**
   * Refresh the access token for a user's connected platform account.
   *
   * @param {string} userId
   * @param {string} platform
   * @returns {Promise<object>}  Updated ConnectedAccount
   */
  async refreshToken(userId, platform) {
    const provider = OAuthProviderFactory.getProvider(platform);
    const result = await provider.refreshToken(userId);
    logger.info('Platform access token refreshed', { userId, platform });
    return result;
  },

  /**
   * Validate whether a user's stored credentials for a platform are still active.
   *
   * @param {string} userId
   * @param {string} platform
   * @returns {Promise<boolean>}
   */
  async validateConnection(userId, platform) {
    const provider = OAuthProviderFactory.getProvider(platform);
    return provider.validateConnection(userId);
  },

  /**
   * Fetch the user's current public profile from a connected platform.
   *
   * @param {string} userId
   * @param {string} platform
   * @returns {Promise<object>}  Normalized profile object
   */
  async getProfile(userId, platform) {
    const provider = OAuthProviderFactory.getProvider(platform);
    return provider.getProfile(userId);
  },
};

export default OAuthService;
